version: 2
jobs:
  build:
    docker:
      - image: menny/android_ndk:1.6.1a
    working_directory: /opt/workspace/
    environment:
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout

      - restore_cache:
          key: checkidnumber-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Permission to scripts
          command: |
            chmod 755 scripts/*

      - run:
          name: Setup environment
          command: |
            ./scripts/ci_setup.sh

      - run:
          name: Run Tests
          command: |
            ./gradlew --no-daemon --stacktrace test -PDisableRibbon

      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: tests_reports_debug/

      - store_artifacts:
          path: app/build/reports/tests/testReleaseUnitTest
          destination: tests_reports_release/

      - store_test_results:
          path: "app/build/test-results/testDebugUnitTest/"

      - save_cache:
                key: checkidnumber-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                paths:
                  - "~/.gradle"
                  - "~/.m2"
